<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>NiyazisugarItemci</AssemblyName>
    <Version>2.7.1</Version>
    <RootNamespace>NiyazisugarItemci</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NiyazisugarUpdater\**\*.cs" />
    <EmbeddedResource Remove="NiyazisugarUpdater\**\*" />
    <None Remove="NiyazisugarUpdater\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.72" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="MarketAnalyzer.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="QuickReplyDock.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="AdBlock.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
